set(_CATKIN_CURRENT_PACKAGE "slider_gazebo")
set(slider_gazebo_VERSION "0.0.0")
set(slider_gazebo_MAINTAINER "kewang <ke.wang17@imperial.ac.uk>")
set(slider_gazebo_PACKAGE_FORMAT "1")
set(slider_gazebo_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "rviz" "std_msgs" "tf" "urdf" "xacro" "std_msgs" "message_generation")
set(slider_gazebo_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "rviz" "std_msgs" "tf" "urdf" "xacro" "message_runtime" "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(slider_gazebo_BUILDTOOL_DEPENDS "catkin")
set(slider_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(slider_gazebo_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "rviz" "std_msgs" "tf" "urdf" "xacro" "message_runtime" "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(slider_gazebo_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "rviz" "std_msgs" "tf" "urdf" "xacro" "message_runtime" "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(slider_gazebo_TEST_DEPENDS )
set(slider_gazebo_DOC_DEPENDS )
set(slider_gazebo_URL_WEBSITE "")
set(slider_gazebo_URL_BUGTRACKER "")
set(slider_gazebo_URL_REPOSITORY "")
set(slider_gazebo_DEPRECATED "")